# Etapas de nuestra pipeline
stages:
  - test

# Job de prueba
test:
  stage: test

  # Comandos ejecutados por el Runner
  script:
    - echo "Hola desde GitLab CI"
    - echo "Pipeline ejecutada correctamente"
    - echo "Proyecto: $CI_PROJECT_NAME"
    - echo "Rama/commit: $CI_COMMIT_REF_NAME"
    - echo "Commit: $CI_COMMIT_SHORT_SHA"